amp: true
batch_size: 2
debug: true
debug_epochs: 10
debug_num_tracks: 2
download_preview: true
early_stop_patience_epochs: 50
epochs: 300
eval_overlap: 0.5
g: 56
latent_dim: 128
lr: 0.0002
lr_factor: 0.9
lr_patience_epochs: 20
multires:
  fft_sizes: !!python/tuple
  - 1024
  - 2048
  - 4096
  hop_sizes: !!python/tuple
  - 256
  - 512
  - 1024
  win_lengths: !!python/tuple
  - 1024
  - 2048
  - 4096
musdb_root: ''
nband: 4
nrope: 5
nsplit_dec: 1
nsplit_enc: 3
num_workers: 4
out_dir: runs/moises_light
sample_rate: 44100
seed: 1337
segment_seconds: 7.0
stft:
  freq_bins: 2048
  hop_length: 1024
  n_fft: 6144
  win_length: 6144
target_stem: vocals
train_overlap: 0.75
trainer:
  accelerator: gpu
  deterministic: false
  devices: 2
  log_every_n_steps: 20
  max_epochs: 300
  precision: 16-mixed
  strategy: ddp
use_multires_loss: true
